class ValueError(Exception):
    pass

class NumeroDebeSerPositivo(Exception):
    pass